// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreatePet(ctx context.Context, arg CreatePetParams) (PetstorePet, error)
	DeletePet(ctx context.Context, id int64) error
	FindPetByID(ctx context.Context, id int64) (PetstorePet, error)
	ListPets(ctx context.Context, tags []string) ([]PetstorePet, error)
	ListPetsWithLimit(ctx context.Context, arg ListPetsWithLimitParams) ([]PetstorePet, error)
}

var _ Querier = (*Queries)(nil)
