version: '3.1'

services:

  db:
    image: ${POSTGRES_IMAGE}
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  petstore:
    image: ${PETSTORE_IMAGE}
    depends_on:
      - db
    restart: always
    environment:
      MIGRATE_DATABASE: "postgres://postgres:${POSTGRES_PASSWORD}@db:5432?sslmode=disable"
      CONNECTION_STRING: "postgresql://postgres:${POSTGRES_PASSWORD}@db:5432"
    ports:
      - "5000:5000"
